// Las 78 cartas del tarot (tradición Rider-Waite-Smith).
// Arcanos mayores: texto propio de cada carta.
// Arcanos menores: palabras clave propias + texto que combina el palo y el número.

const ARCANOS_MAYORES = [
  { n: 0, id: "el-loco", nombre: "El Loco", glifo: "🜁", astro: "Aire",
    claves: ["comienzos", "libertad", "espontaneidad", "fe"],
    invertidas: ["imprudencia", "miedo al salto", "caos"],
    derecho: "Un salto al vacío con el corazón ligero. El Loco abre un ciclo nuevo: algo empieza y todavía no sabes adónde lleva, y eso está bien. Pide confianza, curiosidad y ganas de aprender por el camino.",
    invertido: "El impulso sin mirar dónde pisas. Puede señalar una decisión precipitada o, al revés, el miedo que te impide dar el primer paso. Revisa el mapa antes de saltar.",
    amor: "Una relación fresca y sin guion, o la necesidad de aire dentro de la que ya tienes.",
    trabajo: "Proyecto nuevo, cambio de rumbo o una etapa de aprendizaje. Buena carta para emprender.",
    consejo: "Da el paso, pero lleva lo imprescindible.", sino: "sí" },
  { n: 1, id: "el-mago", nombre: "El Mago", glifo: "☿", astro: "Mercurio",
    claves: ["voluntad", "habilidad", "iniciativa", "recursos"],
    invertidas: ["manipulación", "talento desperdiciado", "engaño"],
    derecho: "Tienes sobre la mesa todo lo que necesitas. El Mago convierte la idea en hecho: concentración, destreza y la decisión de actuar ahora.",
    invertido: "Energía dispersa o mal usada. Cuidado con quien promete mucho y con el truco fácil; también con tu propio talento sin dirección.",
    amor: "Seducción y comunicación. Alguien sabe lo que quiere y va a por ello.",
    trabajo: "Momento ideal para presentar, negociar o lanzar. Tus habilidades están a punto.",
    consejo: "Usa lo que ya tienes. No esperes a tenerlo todo.", sino: "sí" },
  { n: 2, id: "la-sacerdotisa", nombre: "La Sacerdotisa", glifo: "☽", astro: "Luna",
    claves: ["intuición", "misterio", "saber interior", "silencio"],
    invertidas: ["secretos", "desconexión", "superficialidad"],
    derecho: "La respuesta no está fuera. La Sacerdotisa pide escuchar, observar y esperar a que lo oculto se muestre. Hay algo que ya sabes aunque no lo hayas dicho.",
    invertido: "Ignoras tu intuición o alguien oculta información. Ruido que no deja oír lo importante.",
    amor: "Atracción silenciosa, sentimientos no declarados. Tiempo de sentir más que de hablar.",
    trabajo: "Investiga antes de moverte. No todo está sobre la mesa todavía.",
    consejo: "Calla, observa y fíate de tu primera impresión.", sino: "quizás" },
  { n: 3, id: "la-emperatriz", nombre: "La Emperatriz", glifo: "♀", astro: "Venus",
    claves: ["abundancia", "creatividad", "fertilidad", "cuidado"],
    invertidas: ["bloqueo creativo", "dependencia", "descuido"],
    derecho: "Crecimiento, belleza y cosecha. La Emperatriz habla de nutrir lo que amas y de dejar que florezca a su ritmo: proyectos, cuerpo, hogar, familia.",
    invertido: "Te das poco a ti o das demasiado a los demás. La creatividad se atasca cuando falta cuidado propio.",
    amor: "Relación cálida y generosa. Puede anunciar compromiso o familia.",
    trabajo: "Frutos visibles del esfuerzo. Buen momento para crear y embellecer.",
    consejo: "Cuida lo que quieres que crezca, empezando por ti.", sino: "sí" },
  { n: 4, id: "el-emperador", nombre: "El Emperador", glifo: "♈", astro: "Aries",
    claves: ["estructura", "autoridad", "orden", "estabilidad"],
    invertidas: ["rigidez", "control", "abuso de poder"],
    derecho: "Pon orden y toma el mando. El Emperador da forma a las cosas con reglas claras, disciplina y responsabilidad.",
    invertido: "Exceso de control o falta de él. Una figura autoritaria, o tú mismo siendo demasiado rígido.",
    amor: "Estabilidad y protección; cuidado con que se convierta en control.",
    trabajo: "Liderazgo, planificación y ascensos. Trato con jefes o instituciones.",
    consejo: "Ordena primero, avanza después.", sino: "sí" },
  { n: 5, id: "el-hierofante", nombre: "El Hierofante", glifo: "♉", astro: "Tauro",
    claves: ["tradición", "enseñanza", "creencias", "instituciones"],
    invertidas: ["rebeldía", "dogma", "caminos propios"],
    derecho: "Lo aprendido de quienes vinieron antes. El Hierofante señala maestros, normas, ritos y la búsqueda de sentido dentro de un grupo.",
    invertido: "Las reglas ya no te sirven. Toca cuestionar lo heredado y buscar tu propia forma.",
    amor: "Compromiso formal, relación convencional o valores compartidos.",
    trabajo: "Formación, mentores, empresas grandes y procedimientos.",
    consejo: "Pide consejo a quien sabe más.", sino: "sí" },
  { n: 6, id: "los-enamorados", nombre: "Los Enamorados", glifo: "♊", astro: "Géminis",
    claves: ["amor", "elección", "unión", "valores"],
    invertidas: ["desequilibrio", "duda", "mala elección"],
    derecho: "Una elección que nace del corazón y de tus valores. Los Enamorados hablan de unión, pero también de decidir quién eres a través de lo que eliges.",
    invertido: "Indecisión o una relación desequilibrada. Lo que quieres y lo que haces no coinciden.",
    amor: "Carta de amor por excelencia: atracción, armonía y conexión profunda.",
    trabajo: "Una alianza o una decisión importante entre dos caminos.",
    consejo: "Elige lo que esté de acuerdo con lo que valoras.", sino: "sí" },
  { n: 7, id: "el-carro", nombre: "El Carro", glifo: "♋", astro: "Cáncer",
    claves: ["avance", "determinación", "victoria", "control"],
    invertidas: ["dispersión", "agresividad", "falta de rumbo"],
    derecho: "Adelante con fuerza. El Carro gana porque sabe dominar fuerzas opuestas y mantener la dirección.",
    invertido: "Tiras hacia dos lados a la vez. Frustración, falta de control o un avance forzado.",
    amor: "Iniciativa y decisión. Una relación que avanza o un viaje juntos.",
    trabajo: "Éxito por constancia, competición ganada, cambio de puesto o de ciudad.",
    consejo: "Fija el rumbo y no sueltes las riendas.", sino: "sí" },
  { n: 8, id: "la-fuerza", nombre: "La Fuerza", glifo: "♌", astro: "Leo",
    claves: ["valor", "paciencia", "compasión", "dominio interior"],
    invertidas: ["inseguridad", "impulsividad", "debilidad"],
    derecho: "La fuerza tranquila que doma sin golpear. Valor, paciencia y amabilidad para con los propios instintos y los ajenos.",
    invertido: "Dudas de ti o te dejas llevar por el impulso. Recupera la calma antes de actuar.",
    amor: "Una relación que se sostiene con ternura y paciencia.",
    trabajo: "Resistir la presión con temple. Tu constancia convence más que la prisa.",
    consejo: "Suavidad firme: sin gritar, sin ceder.", sino: "sí" },
  { n: 9, id: "el-ermitano", nombre: "El Ermitaño", glifo: "♍", astro: "Virgo",
    claves: ["introspección", "soledad", "búsqueda", "sabiduría"],
    invertidas: ["aislamiento", "retirada excesiva", "soledad no querida"],
    derecho: "Apártate del ruido para ver claro. El Ermitaño alumbra el camino con su propia linterna: reflexión, estudio y un tiempo para ti.",
    invertido: "La soledad se ha vuelto encierro. O te niegas a mirar hacia dentro.",
    amor: "Tiempo para uno mismo antes de compartir. Relación en pausa.",
    trabajo: "Especialización, estudio, trabajo en solitario o un consejo experto.",
    consejo: "Retírate un poco y piénsalo con calma.", sino: "quizás" },
  { n: 10, id: "la-rueda-de-la-fortuna", nombre: "La Rueda de la Fortuna", glifo: "♃", astro: "Júpiter",
    claves: ["ciclos", "cambio", "destino", "suerte"],
    invertidas: ["mala racha", "resistencia al cambio", "estancamiento"],
    derecho: "La rueda gira. Un cambio que no depende del todo de ti y que suele traer oportunidades: aprovecha la subida.",
    invertido: "Una racha a la contra. Todo pasa; aprende del ciclo en lugar de pelearte con él.",
    amor: "Encuentros del destino o un giro inesperado en la relación.",
    trabajo: "Cambios de circunstancias, oportunidades que llegan de golpe.",
    consejo: "Suéltate y adáptate al giro.", sino: "sí" },
  { n: 11, id: "la-justicia", nombre: "La Justicia", glifo: "♎", astro: "Libra",
    claves: ["equilibrio", "verdad", "causa y efecto", "decisión"],
    invertidas: ["injusticia", "parcialidad", "evitar responsabilidades"],
    derecho: "Cada cosa en su sitio. La Justicia pesa los hechos con honestidad: recibes lo que corresponde y decides con la cabeza fría.",
    invertido: "Algo no es justo, o tú no estás asumiendo tu parte. Revisa con honradez.",
    amor: "Relación equilibrada, acuerdos claros. Puede hablar de papeles.",
    trabajo: "Contratos, asuntos legales, decisiones objetivas.",
    consejo: "Sé honesto contigo y con los demás.", sino: "quizás" },
  { n: 12, id: "el-colgado", nombre: "El Colgado", glifo: "🜄", astro: "Agua",
    claves: ["pausa", "otra perspectiva", "entrega", "sacrificio"],
    invertidas: ["estancamiento", "resistencia", "sacrificio inútil"],
    derecho: "Colgado del revés, el mundo se ve distinto. Una pausa necesaria: soltar el control y mirar la situación desde otro ángulo.",
    invertido: "Esperas sin sentido o te resistes a lo inevitable. Deja de aplazar.",
    amor: "Relación en suspenso. Hay que ver las cosas desde el lado del otro.",
    trabajo: "Proyecto parado. Aprovecha para replantearlo.",
    consejo: "No fuerces: cambia el punto de vista.", sino: "quizás" },
  { n: 13, id: "la-muerte", nombre: "La Muerte", glifo: "♏", astro: "Escorpio",
    claves: ["final", "transformación", "cierre", "renovación"],
    invertidas: ["resistencia al cambio", "estancamiento", "miedo"],
    derecho: "No anuncia una muerte física: anuncia un final. Algo termina para que otra cosa pueda nacer. Es una de las cartas más transformadoras.",
    invertido: "Te aferras a lo que ya acabó. El cambio llegará igual; mejor acompañarlo.",
    amor: "Una etapa que se cierra, o una relación que se transforma por completo.",
    trabajo: "Fin de un empleo o de una forma de trabajar. Espacio para lo nuevo.",
    consejo: "Suelta lo que ya terminó.", sino: "no" },
  { n: 14, id: "la-templanza", nombre: "La Templanza", glifo: "♐", astro: "Sagitario",
    claves: ["equilibrio", "moderación", "paciencia", "sanación"],
    invertidas: ["exceso", "desequilibrio", "prisa"],
    derecho: "La mezcla justa. La Templanza combina opuestos con paciencia y encuentra el punto medio: calma, salud y armonía.",
    invertido: "Te pasas o te quedas corto. Algo pide más paciencia y menos extremos.",
    amor: "Relación serena, reconciliación, entendimiento.",
    trabajo: "Colaboración, ritmo sostenible, buena gestión.",
    consejo: "Ni tanto ni tan poco.", sino: "sí" },
  { n: 15, id: "el-diablo", nombre: "El Diablo", glifo: "♑", astro: "Capricornio",
    claves: ["ataduras", "tentación", "materialismo", "deseo"],
    invertidas: ["liberación", "romper cadenas", "tomar conciencia"],
    derecho: "Las cadenas que llevas puestas… y que podrías quitarte. El Diablo muestra dependencias, excesos y relaciones que atan.",
    invertido: "Empiezas a ver la trampa y a salir de ella. Liberación.",
    amor: "Pasión intensa, pero también posesividad o dependencia.",
    trabajo: "Un trabajo que te ata por dinero. Cuidado con los tratos turbios.",
    consejo: "Mira qué te tiene atado y por qué lo permites.", sino: "no" },
  { n: 16, id: "la-torre", nombre: "La Torre", glifo: "♂", astro: "Marte",
    claves: ["ruptura", "revelación", "cambio súbito", "liberación"],
    invertidas: ["evitar el desastre", "miedo al cambio", "crisis interna"],
    derecho: "El rayo derriba lo que estaba mal construido. Un cambio brusco, a veces doloroso, que deja ver la verdad y despeja el terreno.",
    invertido: "Una crisis que intentas contener, o que vives por dentro. Aplazarla no la evita.",
    amor: "Ruptura o una verdad que lo cambia todo.",
    trabajo: "Cambios repentinos, reestructuraciones, planes que caen.",
    consejo: "Deja caer lo que no se sostiene.", sino: "no" },
  { n: 17, id: "la-estrella", nombre: "La Estrella", glifo: "♒", astro: "Acuario",
    claves: ["esperanza", "inspiración", "renovación", "serenidad"],
    invertidas: ["desánimo", "falta de fe", "desconexión"],
    derecho: "Tras la tormenta, la calma. La Estrella trae esperanza, sanación y la sensación de que vas por buen camino.",
    invertido: "Has perdido la fe en ti. La luz sigue ahí aunque ahora no la veas.",
    amor: "Amor sincero y sanador. Nuevas ilusiones.",
    trabajo: "Inspiración, reconocimiento, proyectos con futuro.",
    consejo: "Confía: lo peor ya pasó.", sino: "sí" },
  { n: 18, id: "la-luna", nombre: "La Luna", glifo: "♓", astro: "Piscis",
    claves: ["ilusión", "miedo", "subconsciente", "incertidumbre"],
    invertidas: ["claridad que llega", "miedos que se disipan", "confusión"],
    derecho: "No todo es lo que parece. La Luna ilumina a medias: sueños, intuiciones, miedos y cosas ocultas. Avanza despacio.",
    invertido: "La niebla empieza a levantarse. Los miedos pierden fuerza.",
    amor: "Dudas, celos o algo que no se dice. Mucha emoción, poca claridad.",
    trabajo: "Información incompleta. No firmes a ciegas.",
    consejo: "No decidas hasta ver claro.", sino: "no" },
  { n: 19, id: "el-sol", nombre: "El Sol", glifo: "☉", astro: "Sol",
    claves: ["alegría", "éxito", "vitalidad", "claridad"],
    invertidas: ["optimismo excesivo", "alegría retrasada", "ego"],
    derecho: "La carta más luminosa del mazo. Éxito, alegría, salud y verdad a plena luz. Todo se ve claro.",
    invertido: "La alegría llega, pero con retraso o a medias. Cuidado con el exceso de confianza.",
    amor: "Felicidad compartida, relación sana y visible.",
    trabajo: "Éxito, reconocimiento, resultados que se ven.",
    consejo: "Disfruta y déjate ver.", sino: "sí" },
  { n: 20, id: "el-juicio", nombre: "El Juicio", glifo: "🜂", astro: "Fuego",
    claves: ["despertar", "renacer", "llamada", "balance"],
    invertidas: ["autocrítica", "dudas", "ignorar la llamada"],
    derecho: "Una llamada que no puedes ignorar. El Juicio es hacer balance, perdonarte y renacer a una etapa nueva con lo aprendido.",
    invertido: "Te juzgas demasiado o no quieres escuchar lo que ya sabes.",
    amor: "Segundas oportunidades, reencuentros, decisiones de fondo.",
    trabajo: "Evaluaciones, vocación, un cambio de profesión que te llama.",
    consejo: "Escucha la llamada y responde.", sino: "sí" },
  { n: 21, id: "el-mundo", nombre: "El Mundo", glifo: "♄", astro: "Saturno",
    claves: ["plenitud", "logro", "cierre de ciclo", "viajes"],
    invertidas: ["algo sin terminar", "atajos", "falta de cierre"],
    derecho: "El círculo se completa. El Mundo es el logro, la plenitud y el final feliz de un ciclo largo. También viajes y horizontes amplios.",
    invertido: "Te falta un último paso para cerrar. No lo dejes a medias.",
    amor: "Relación plena y madura, o la llegada de lo que esperabas.",
    trabajo: "Metas cumplidas, proyectos terminados, trabajo internacional.",
    consejo: "Termina lo que empezaste y celébralo.", sino: "sí" },
];

const PALOS = {
  bastos: { nombre: "Bastos", elemento: "Fuego", glifo: "🜂", ambito: "la acción, la energía, la ambición y la creatividad",
    corto: "energía y acción" },
  copas: { nombre: "Copas", elemento: "Agua", glifo: "🜄", ambito: "las emociones, el amor, las relaciones y la intuición",
    corto: "emociones y vínculos" },
  espadas: { nombre: "Espadas", elemento: "Aire", glifo: "🜁", ambito: "la mente, las ideas, los conflictos y la verdad",
    corto: "mente y conflicto" },
  oros: { nombre: "Oros", elemento: "Tierra", glifo: "⛤", ambito: "el dinero, el trabajo, el cuerpo y lo material",
    corto: "dinero y lo material" },
};

const RANGOS = [
  { r: 1, nombre: "As", sentido: "el inicio en estado puro: una semilla, una oportunidad nueva", inv: "una oportunidad que se retrasa o se desaprovecha" },
  { r: 2, nombre: "Dos", sentido: "el equilibrio entre dos fuerzas, la decisión o la pareja", inv: "el desequilibrio o la indecisión" },
  { r: 3, nombre: "Tres", sentido: "el primer crecimiento y la colaboración", inv: "los retrasos y la falta de entendimiento" },
  { r: 4, nombre: "Cuatro", sentido: "la estabilidad y la base firme", inv: "el estancamiento o la rigidez" },
  { r: 5, nombre: "Cinco", sentido: "el conflicto, la pérdida o la prueba", inv: "la recuperación tras el golpe" },
  { r: 6, nombre: "Seis", sentido: "la armonía recuperada y el avance", inv: "el retroceso o la nostalgia que frena" },
  { r: 7, nombre: "Siete", sentido: "la evaluación, la estrategia y la perseverancia", inv: "la duda y el agotamiento" },
  { r: 8, nombre: "Ocho", sentido: "el movimiento, el cambio y la maestría", inv: "la inercia y el bloqueo" },
  { r: 9, nombre: "Nueve", sentido: "casi en la meta: la plenitud o su última prueba", inv: "la ansiedad justo antes del final" },
  { r: 10, nombre: "Diez", sentido: "el ciclo completo, con su logro y su peso", inv: "el exceso o un cierre que cuesta" },
  { r: 11, nombre: "Sota", sentido: "el aprendiz: noticias, curiosidad y ganas de empezar", inv: "la inmadurez o las malas noticias" },
  { r: 12, nombre: "Caballo", sentido: "la acción decidida y el movimiento rápido", inv: "la impaciencia o los excesos" },
  { r: 13, nombre: "Reina", sentido: "el dominio interior, maduro y receptivo", inv: "la inseguridad o la manipulación" },
  { r: 14, nombre: "Rey", sentido: "el dominio exterior, maduro y firme", inv: "el autoritarismo o el mal uso del poder" },
];

// Palabras clave propias de cada arcano menor: [derecho, invertido]
const CLAVES_MENORES = {
  bastos: [
    ["inspiración, nuevo proyecto, impulso", "retrasos, falta de motivación"],
    ["planificación, decisiones, horizontes", "miedo a lo desconocido, falta de planes"],
    ["expansión, previsión, oportunidades lejanas", "obstáculos, retrasos en el crecimiento"],
    ["celebración, hogar, estabilidad alegre", "tensión en casa, transición"],
    ["competencia, rivalidad, desacuerdos", "evitar el conflicto, tregua"],
    ["victoria, reconocimiento, progreso", "ego, caída de la fama"],
    ["defensa, perseverancia, desafío", "agotamiento, rendirse"],
    ["rapidez, noticias, movimiento", "prisas, frenazo, esperas"],
    ["resiliencia, última prueba, límites", "cansancio, paranoia"],
    ["carga, responsabilidad, esfuerzo", "delegar, soltar peso"],
    ["entusiasmo, exploración, ideas", "impaciencia, ideas sin rumbo"],
    ["aventura, pasión, impulsividad", "temeridad, precipitación"],
    ["confianza, carisma, determinación", "celos, inseguridad"],
    ["liderazgo, visión, emprendimiento", "impulsividad, arrogancia"],
  ],
  copas: [
    ["amor nuevo, emoción, intuición", "vacío emocional, sentimientos bloqueados"],
    ["unión, pareja, atracción mutua", "desequilibrio, ruptura"],
    ["amistad, celebración, comunidad", "excesos, cotilleos"],
    ["apatía, contemplación, reevaluar", "despertar, aceptar lo ofrecido"],
    ["pérdida, pena, arrepentimiento", "aceptación, seguir adelante"],
    ["nostalgia, recuerdos, inocencia", "vivir en el pasado, soltar"],
    ["ilusiones, opciones, fantasía", "claridad, decidir"],
    ["abandono, marcharse, buscar más", "miedo a irse, deriva"],
    ["deseo cumplido, satisfacción", "insatisfacción, materialismo"],
    ["armonía familiar, felicidad plena", "desarmonía, valores distintos"],
    ["mensaje emocional, sensibilidad, creatividad", "inmadurez emocional"],
    ["romance, propuesta, encanto", "celos, expectativas irreales"],
    ["compasión, intuición, cuidado", "dependencia emocional"],
    ["equilibrio emocional, diplomacia", "manipulación, frialdad"],
  ],
  espadas: [
    ["claridad, verdad, idea brillante", "confusión, ideas nubladas"],
    ["decisión difícil, bloqueo, tregua", "indecisión, información oculta"],
    ["dolor, desengaño, tristeza", "recuperación, perdón"],
    ["descanso, recuperación, pausa", "agotamiento, inquietud"],
    ["conflicto, derrota, ganar a toda costa", "reconciliación, rencor que se suelta"],
    ["transición, dejar atrás, viaje", "equipaje emocional, asuntos pendientes"],
    ["estrategia, astucia, engaño", "confesión, conciencia"],
    ["encierro, limitación, víctima", "liberación, nueva perspectiva"],
    ["ansiedad, insomnio, preocupación", "esperanza, ayuda"],
    ["final doloroso, tocar fondo", "recuperación, lo peor pasó"],
    ["curiosidad, vigilancia, ideas nuevas", "cotilleo, prisas"],
    ["ambición, acción rápida, franqueza", "impulsividad, agresividad"],
    ["independencia, lucidez, límites claros", "frialdad, amargura"],
    ["autoridad intelectual, verdad, ética", "abuso de poder, crueldad"],
  ],
  oros: [
    ["oportunidad material, prosperidad", "oportunidad perdida, mala planificación"],
    ["malabares, adaptabilidad, prioridades", "desorden, exceso de frentes"],
    ["trabajo en equipo, oficio, aprendizaje", "falta de colaboración"],
    ["ahorro, seguridad, control", "avaricia, miedo a perder"],
    ["escasez, dificultad, exclusión", "recuperación económica, ayuda"],
    ["generosidad, dar y recibir", "deudas, generosidad interesada"],
    ["paciencia, inversión, esperar frutos", "impaciencia, esfuerzo sin fruto"],
    ["dedicación, oficio, detalle", "perfeccionismo, rutina"],
    ["independencia, lujo merecido", "dependencia económica"],
    ["patrimonio, familia, legado", "pérdidas, conflictos por herencias"],
    ["estudio, ambición práctica, noticias de dinero", "falta de foco, pereza"],
    ["constancia, rutina, responsabilidad", "estancamiento, aburrimiento"],
    ["sentido práctico, cuidado, abundancia", "descuido, desequilibrio trabajo-hogar"],
    ["riqueza, éxito, seguridad", "materialismo, terquedad"],
  ],
};

function construirMenores() {
  const lista = [];
  for (const [palo, datos] of Object.entries(PALOS)) {
    RANGOS.forEach((rango, i) => {
      const [cd, ci] = CLAVES_MENORES[palo][i];
      const nombre = `${rango.nombre} de ${datos.nombre}`;
      lista.push({
        id: `${rango.nombre.toLowerCase()}-de-${palo}`,
        nombre, palo, rango: rango.r, glifo: datos.glifo, astro: datos.elemento,
        claves: cd.split(", "), invertidas: ci.split(", "),
        derecho: `${nombre} pertenece al terreno de ${datos.ambito}. Representa ${rango.sentido}. Sus palabras clave: ${cd}.`.replace(" de el ", " del "),
        invertido: `Invertida, la carta apunta a ${rango.inv} en el terreno de ${datos.corto}. Sus palabras clave: ${ci}.`,
        amor: palo === "copas" ? `Muy importante en temas del corazón: ${cd}.` : `En el amor, trasladado a la pareja: ${cd}.`,
        trabajo: palo === "oros" || palo === "bastos" ? `Muy relevante en lo laboral: ${cd}.` : `En el trabajo: ${cd}.`,
        consejo: `La clave ahora: ${cd.split(", ")[0]}.`,
        sino: rango.r === 5 || (palo === "espadas" && [3, 8, 9, 10].includes(rango.r)) ? "no" : ([4, 7, 12].includes(rango.r) ? "quizás" : "sí"),
      });
    });
  }
  return lista;
}

const ARCANOS_MENORES = construirMenores();
const MAZO = [...ARCANOS_MAYORES.map(c => ({ ...c, mayor: true })), ...ARCANOS_MENORES.map(c => ({ ...c, mayor: false }))];
const cartaPorId = id => MAZO.find(c => c.id === id);

const NUMERALES = ["0", "I", "II", "III", "IV", "V", "VI", "VII", "VIII", "IX", "X", "XI", "XII", "XIII", "XIV", "XV", "XVI", "XVII", "XVIII", "XIX", "XX", "XXI"];
