// The 78 tarot cards (Rider-Waite-Smith tradition) — English version.
// Same ids and structure as js/cartas.js; "sino" keeps the internal codes "sí" / "no" / "quizás".

const ARCANOS_MAYORES = [
  { n: 0, id: "el-loco", nombre: "The Fool", glifo: "🜁", astro: "Air",
    claves: ["beginnings", "freedom", "spontaneity", "faith"], invertidas: ["recklessness", "fear of the leap", "chaos"],
    derecho: "A leap into the unknown with a light heart. The Fool opens a new cycle: something is starting and you don't know yet where it leads, and that's fine. It asks for trust, curiosity and the willingness to learn along the way.",
    invertido: "Impulse without looking where you step. It can point to a rushed decision or, the other way round, to the fear that stops you from taking the first step. Check the map before you jump.",
    amor: "A fresh relationship with no script, or the need for more air in the one you have.",
    trabajo: "A new project, a change of direction or a learning phase. A good card for starting something.",
    consejo: "Take the step, but pack the essentials.", sino: "sí" },
  { n: 1, id: "el-mago", nombre: "The Magician", glifo: "☿", astro: "Mercury",
    claves: ["willpower", "skill", "initiative", "resources"], invertidas: ["manipulation", "wasted talent", "deception"],
    derecho: "Everything you need is already on the table. The Magician turns ideas into action: focus, skill and the decision to act now.",
    invertido: "Scattered or misused energy. Beware of whoever promises too much and of the easy trick — and of your own talent without direction.",
    amor: "Charm and communication. Someone knows what they want and goes for it.",
    trabajo: "The perfect moment to pitch, negotiate or launch. Your skills are ready.",
    consejo: "Use what you already have. Don't wait to have it all.", sino: "sí" },
  { n: 2, id: "la-sacerdotisa", nombre: "The High Priestess", glifo: "☽", astro: "Moon",
    claves: ["intuition", "mystery", "inner knowing", "silence"], invertidas: ["secrets", "disconnection", "shallowness"],
    derecho: "The answer isn't outside. The High Priestess asks you to listen, observe and wait for what's hidden to show itself. There's something you already know even if you haven't said it.",
    invertido: "You're ignoring your intuition or someone is hiding information. Noise that drowns out what matters.",
    amor: "Silent attraction, unspoken feelings. A time to feel rather than talk.",
    trabajo: "Research before you move. Not everything is on the table yet.",
    consejo: "Stay quiet, watch, and trust your first impression.", sino: "quizás" },
  { n: 3, id: "la-emperatriz", nombre: "The Empress", glifo: "♀", astro: "Venus",
    claves: ["abundance", "creativity", "fertility", "care"], invertidas: ["creative block", "dependence", "neglect"],
    derecho: "Growth, beauty and harvest. The Empress is about nurturing what you love and letting it bloom at its own pace: projects, body, home, family.",
    invertido: "You give too little to yourself or too much to others. Creativity gets stuck when self-care is missing.",
    amor: "A warm, generous relationship. It may announce commitment or family.",
    trabajo: "Visible results from your effort. A good time to create and make things beautiful.",
    consejo: "Look after what you want to grow, starting with yourself.", sino: "sí" },
  { n: 4, id: "el-emperador", nombre: "The Emperor", glifo: "♈", astro: "Aries",
    claves: ["structure", "authority", "order", "stability"], invertidas: ["rigidity", "control", "abuse of power"],
    derecho: "Bring order and take charge. The Emperor gives shape to things with clear rules, discipline and responsibility.",
    invertido: "Too much control, or too little. An authoritarian figure, or you being too rigid.",
    amor: "Stability and protection — careful it doesn't turn into control.",
    trabajo: "Leadership, planning and promotions. Dealing with bosses or institutions.",
    consejo: "Get organised first, move forward second.", sino: "sí" },
  { n: 5, id: "el-hierofante", nombre: "The Hierophant", glifo: "♉", astro: "Taurus",
    claves: ["tradition", "teaching", "beliefs", "institutions"], invertidas: ["rebellion", "dogma", "your own path"],
    derecho: "What we learn from those who came before. The Hierophant points to teachers, rules, rituals and the search for meaning within a group.",
    invertido: "The rules no longer work for you. Time to question what you inherited and find your own way.",
    amor: "Formal commitment, a traditional relationship or shared values.",
    trabajo: "Training, mentors, large companies and procedures.",
    consejo: "Ask for advice from someone who knows more.", sino: "sí" },
  { n: 6, id: "los-enamorados", nombre: "The Lovers", glifo: "♊", astro: "Gemini",
    claves: ["love", "choice", "union", "values"], invertidas: ["imbalance", "doubt", "wrong choice"],
    derecho: "A choice that comes from the heart and from your values. The Lovers speak of union, but also of deciding who you are through what you choose.",
    invertido: "Indecision or an unbalanced relationship. What you want and what you do don't match.",
    amor: "The love card par excellence: attraction, harmony and deep connection.",
    trabajo: "A partnership or an important decision between two paths.",
    consejo: "Choose what fits what you value.", sino: "sí" },
  { n: 7, id: "el-carro", nombre: "The Chariot", glifo: "♋", astro: "Cancer",
    claves: ["progress", "determination", "victory", "control"], invertidas: ["scattered energy", "aggression", "lack of direction"],
    derecho: "Full speed ahead. The Chariot wins because it can steer opposing forces and keep its direction.",
    invertido: "You're pulling in two directions at once. Frustration, loss of control or forced progress.",
    amor: "Initiative and decision. A relationship moving forward or a trip together.",
    trabajo: "Success through persistence, a competition won, a change of job or city.",
    consejo: "Set your course and don't let go of the reins.", sino: "sí" },
  { n: 8, id: "la-fuerza", nombre: "Strength", glifo: "♌", astro: "Leo",
    claves: ["courage", "patience", "compassion", "inner strength"], invertidas: ["insecurity", "impulsiveness", "weakness"],
    derecho: "The quiet strength that tames without striking. Courage, patience and kindness towards your own instincts and other people's.",
    invertido: "You doubt yourself or let impulse take over. Find your calm before acting.",
    amor: "A relationship held together by tenderness and patience.",
    trabajo: "Withstanding pressure with composure. Your steadiness convinces more than haste.",
    consejo: "Gentle but firm: no shouting, no giving in.", sino: "sí" },
  { n: 9, id: "el-ermitano", nombre: "The Hermit", glifo: "♍", astro: "Virgo",
    claves: ["introspection", "solitude", "search", "wisdom"], invertidas: ["isolation", "withdrawing too much", "unwanted loneliness"],
    derecho: "Step away from the noise to see clearly. The Hermit lights the way with his own lantern: reflection, study and time for yourself.",
    invertido: "Solitude has become a cage. Or you refuse to look inwards.",
    amor: "Time for yourself before sharing. A relationship on pause.",
    trabajo: "Specialising, studying, working alone or expert advice.",
    consejo: "Step back a little and think it through calmly.", sino: "quizás" },
  { n: 10, id: "la-rueda-de-la-fortuna", nombre: "Wheel of Fortune", glifo: "♃", astro: "Jupiter",
    claves: ["cycles", "change", "destiny", "luck"], invertidas: ["bad luck", "resisting change", "stagnation"],
    derecho: "The wheel turns. A change that isn't entirely up to you and usually brings opportunities: make the most of the upswing.",
    invertido: "A losing streak. Everything passes; learn from the cycle instead of fighting it.",
    amor: "Fateful encounters or an unexpected turn in the relationship.",
    trabajo: "Changing circumstances, opportunities that arrive all at once.",
    consejo: "Let go and adapt to the turn.", sino: "sí" },
  { n: 11, id: "la-justicia", nombre: "Justice", glifo: "♎", astro: "Libra",
    claves: ["balance", "truth", "cause and effect", "decision"], invertidas: ["injustice", "bias", "avoiding responsibility"],
    derecho: "Everything in its place. Justice weighs the facts honestly: you get what you're due and decide with a cool head.",
    invertido: "Something isn't fair, or you're not owning your part. Take an honest look.",
    amor: "A balanced relationship, clear agreements. It may involve paperwork.",
    trabajo: "Contracts, legal matters, objective decisions.",
    consejo: "Be honest with yourself and with others.", sino: "quizás" },
  { n: 12, id: "el-colgado", nombre: "The Hanged Man", glifo: "🜄", astro: "Water",
    claves: ["pause", "new perspective", "surrender", "sacrifice"], invertidas: ["stagnation", "resistance", "pointless sacrifice"],
    derecho: "Hanging upside down, the world looks different. A necessary pause: let go of control and look at the situation from another angle.",
    invertido: "Waiting for nothing, or resisting the inevitable. Stop putting it off.",
    amor: "A relationship on hold. Try seeing things from the other person's side.",
    trabajo: "A stalled project. Use the pause to rethink it.",
    consejo: "Don't force it: change your point of view.", sino: "quizás" },
  { n: 13, id: "la-muerte", nombre: "Death", glifo: "♏", astro: "Scorpio",
    claves: ["ending", "transformation", "closure", "renewal"], invertidas: ["resisting change", "stagnation", "fear"],
    derecho: "It doesn't announce a physical death: it announces an ending. Something finishes so that something else can be born. One of the most transformative cards in the deck.",
    invertido: "You're clinging to what's already over. Change will come anyway; better to go with it.",
    amor: "A chapter closes, or a relationship transforms completely.",
    trabajo: "The end of a job or a way of working. Room for something new.",
    consejo: "Let go of what's already finished.", sino: "no" },
  { n: 14, id: "la-templanza", nombre: "Temperance", glifo: "♐", astro: "Sagittarius",
    claves: ["balance", "moderation", "patience", "healing"], invertidas: ["excess", "imbalance", "haste"],
    derecho: "The right blend. Temperance mixes opposites patiently and finds the middle ground: calm, health and harmony.",
    invertido: "Too much or too little. Something needs more patience and fewer extremes.",
    amor: "A calm relationship, reconciliation, understanding.",
    trabajo: "Collaboration, a sustainable pace, good management.",
    consejo: "Not too much, not too little.", sino: "sí" },
  { n: 15, id: "el-diablo", nombre: "The Devil", glifo: "♑", astro: "Capricorn",
    claves: ["attachment", "temptation", "materialism", "desire"], invertidas: ["release", "breaking chains", "awareness"],
    derecho: "The chains you're wearing… and could take off. The Devil shows dependencies, excess and relationships that bind.",
    invertido: "You're starting to see the trap and get out of it. Liberation.",
    amor: "Intense passion, but also possessiveness or dependence.",
    trabajo: "A job that ties you down for the money. Beware of shady deals.",
    consejo: "Look at what's holding you and why you allow it.", sino: "no" },
  { n: 16, id: "la-torre", nombre: "The Tower", glifo: "♂", astro: "Mars",
    claves: ["upheaval", "revelation", "sudden change", "liberation"], invertidas: ["averting disaster", "fear of change", "inner crisis"],
    derecho: "Lightning brings down what was badly built. A sudden, sometimes painful change that reveals the truth and clears the ground.",
    invertido: "A crisis you're trying to contain, or living inside. Postponing it won't avoid it.",
    amor: "A break-up, or a truth that changes everything.",
    trabajo: "Sudden changes, restructuring, plans falling through.",
    consejo: "Let what can't stand fall.", sino: "no" },
  { n: 17, id: "la-estrella", nombre: "The Star", glifo: "♒", astro: "Aquarius",
    claves: ["hope", "inspiration", "renewal", "serenity"], invertidas: ["discouragement", "lack of faith", "disconnection"],
    derecho: "After the storm, the calm. The Star brings hope, healing and the feeling that you're on the right path.",
    invertido: "You've lost faith in yourself. The light is still there even if you can't see it now.",
    amor: "Sincere, healing love. New hopes.",
    trabajo: "Inspiration, recognition, projects with a future.",
    consejo: "Trust: the worst is behind you.", sino: "sí" },
  { n: 18, id: "la-luna", nombre: "The Moon", glifo: "♓", astro: "Pisces",
    claves: ["illusion", "fear", "the subconscious", "uncertainty"], invertidas: ["clarity arriving", "fears fading", "confusion"],
    derecho: "Not everything is what it seems. The Moon only half-lights the way: dreams, hunches, fears and hidden things. Move slowly.",
    invertido: "The fog is starting to lift. Your fears are losing their grip.",
    amor: "Doubts, jealousy or something left unsaid. Lots of emotion, little clarity.",
    trabajo: "Incomplete information. Don't sign blindly.",
    consejo: "Don't decide until you see clearly.", sino: "no" },
  { n: 19, id: "el-sol", nombre: "The Sun", glifo: "☉", astro: "Sun",
    claves: ["joy", "success", "vitality", "clarity"], invertidas: ["overconfidence", "delayed joy", "ego"],
    derecho: "The brightest card in the deck. Success, joy, health and truth in broad daylight. Everything is clear.",
    invertido: "The joy is coming, but late or only halfway. Watch out for overconfidence.",
    amor: "Shared happiness, a healthy relationship out in the open.",
    trabajo: "Success, recognition, visible results.",
    consejo: "Enjoy it and let yourself be seen.", sino: "sí" },
  { n: 20, id: "el-juicio", nombre: "Judgement", glifo: "🜂", astro: "Fire",
    claves: ["awakening", "rebirth", "calling", "reckoning"], invertidas: ["self-criticism", "doubt", "ignoring the call"],
    derecho: "A call you can't ignore. Judgement is about taking stock, forgiving yourself and being reborn into a new stage with what you've learned.",
    invertido: "You judge yourself too harshly, or you won't listen to what you already know.",
    amor: "Second chances, reunions, deep decisions.",
    trabajo: "Evaluations, vocation, a career change that's calling you.",
    consejo: "Hear the call and answer it.", sino: "sí" },
  { n: 21, id: "el-mundo", nombre: "The World", glifo: "♄", astro: "Saturn",
    claves: ["fulfilment", "achievement", "completion", "travel"], invertidas: ["something unfinished", "shortcuts", "lack of closure"],
    derecho: "The circle is complete. The World is achievement, fulfilment and the happy ending of a long cycle. Also travel and wide horizons.",
    invertido: "One last step is missing to close the circle. Don't leave it halfway.",
    amor: "A full, mature relationship, or the arrival of what you were waiting for.",
    trabajo: "Goals reached, projects finished, international work.",
    consejo: "Finish what you started and celebrate it.", sino: "sí" },
];

const PALOS = {
  bastos: { nombre: "Wands", elemento: "Fire", glifo: "🜂", ambito: "action, energy, ambition and creativity", corto: "energy and action" },
  copas: { nombre: "Cups", elemento: "Water", glifo: "🜄", ambito: "emotions, love, relationships and intuition", corto: "emotions and relationships" },
  espadas: { nombre: "Swords", elemento: "Air", glifo: "🜁", ambito: "the mind, ideas, conflict and truth", corto: "the mind and conflict" },
  oros: { nombre: "Pentacles", elemento: "Earth", glifo: "⛤", ambito: "money, work, the body and material things", corto: "money and material things" },
};

const RANGOS = [
  { r: 1, nombre: "Ace", sentido: "a beginning in its purest form: a seed, a new opportunity", inv: "an opportunity that's delayed or missed" },
  { r: 2, nombre: "Two", sentido: "the balance between two forces, a decision or a partnership", inv: "imbalance or indecision" },
  { r: 3, nombre: "Three", sentido: "first growth and collaboration", inv: "delays and misunderstandings" },
  { r: 4, nombre: "Four", sentido: "stability and solid foundations", inv: "stagnation or rigidity" },
  { r: 5, nombre: "Five", sentido: "conflict, loss or a test", inv: "recovery after the blow" },
  { r: 6, nombre: "Six", sentido: "harmony regained and moving forward", inv: "setbacks or nostalgia that holds you back" },
  { r: 7, nombre: "Seven", sentido: "assessment, strategy and perseverance", inv: "doubt and exhaustion" },
  { r: 8, nombre: "Eight", sentido: "movement, change and mastery", inv: "inertia and blockage" },
  { r: 9, nombre: "Nine", sentido: "almost there: fulfilment or its final test", inv: "anxiety just before the end" },
  { r: 10, nombre: "Ten", sentido: "a completed cycle, with its reward and its weight", inv: "excess or a hard ending" },
  { r: 11, nombre: "Page", sentido: "the apprentice: news, curiosity and eagerness to start", inv: "immaturity or bad news" },
  { r: 12, nombre: "Knight", sentido: "decisive action and fast movement", inv: "impatience or excess" },
  { r: 13, nombre: "Queen", sentido: "inner mastery, mature and receptive", inv: "insecurity or manipulation" },
  { r: 14, nombre: "King", sentido: "outer mastery, mature and firm", inv: "authoritarianism or misuse of power" },
];

const CLAVES_MENORES = {
  bastos: [
    ["inspiration, new project, drive", "delays, lack of motivation"],
    ["planning, decisions, horizons", "fear of the unknown, no plan"],
    ["expansion, foresight, distant opportunities", "obstacles, slow growth"],
    ["celebration, home, joyful stability", "tension at home, transition"],
    ["competition, rivalry, disagreements", "avoiding conflict, truce"],
    ["victory, recognition, progress", "ego, fall from grace"],
    ["defence, perseverance, challenge", "exhaustion, giving up"],
    ["speed, news, movement", "rushing, sudden halt, waiting"],
    ["resilience, final test, boundaries", "fatigue, paranoia"],
    ["burden, responsibility, effort", "delegating, letting go"],
    ["enthusiasm, exploration, ideas", "impatience, aimless ideas"],
    ["adventure, passion, impulsiveness", "recklessness, haste"],
    ["confidence, charisma, determination", "jealousy, insecurity"],
    ["leadership, vision, entrepreneurship", "impulsiveness, arrogance"],
  ],
  copas: [
    ["new love, emotion, intuition", "emotional emptiness, blocked feelings"],
    ["union, partnership, mutual attraction", "imbalance, break-up"],
    ["friendship, celebration, community", "excess, gossip"],
    ["apathy, contemplation, re-evaluation", "awakening, accepting what's offered"],
    ["loss, grief, regret", "acceptance, moving on"],
    ["nostalgia, memories, innocence", "living in the past, letting go"],
    ["illusions, options, fantasy", "clarity, deciding"],
    ["walking away, leaving, seeking more", "fear of leaving, drifting"],
    ["wish fulfilled, satisfaction", "dissatisfaction, materialism"],
    ["family harmony, complete happiness", "disharmony, different values"],
    ["emotional message, sensitivity, creativity", "emotional immaturity"],
    ["romance, proposal, charm", "jealousy, unrealistic expectations"],
    ["compassion, intuition, care", "emotional dependence"],
    ["emotional balance, diplomacy", "manipulation, coldness"],
  ],
  espadas: [
    ["clarity, truth, a brilliant idea", "confusion, clouded thinking"],
    ["difficult decision, stalemate, truce", "indecision, hidden information"],
    ["heartache, disappointment, sorrow", "recovery, forgiveness"],
    ["rest, recovery, pause", "exhaustion, restlessness"],
    ["conflict, defeat, winning at all costs", "reconciliation, letting go of resentment"],
    ["transition, leaving behind, journey", "emotional baggage, unfinished business"],
    ["strategy, cunning, deception", "confession, conscience"],
    ["feeling trapped, limitation, victimhood", "release, new perspective"],
    ["anxiety, sleeplessness, worry", "hope, help"],
    ["painful ending, rock bottom", "recovery, the worst is over"],
    ["curiosity, vigilance, new ideas", "gossip, haste"],
    ["ambition, fast action, directness", "impulsiveness, aggression"],
    ["independence, clarity, clear boundaries", "coldness, bitterness"],
    ["intellectual authority, truth, ethics", "abuse of power, cruelty"],
  ],
  oros: [
    ["material opportunity, prosperity", "missed opportunity, poor planning"],
    ["juggling, adaptability, priorities", "disorder, too many fronts"],
    ["teamwork, craft, learning", "lack of collaboration"],
    ["saving, security, control", "greed, fear of losing"],
    ["hardship, difficulty, exclusion", "financial recovery, help"],
    ["generosity, giving and receiving", "debts, strings-attached generosity"],
    ["patience, investment, waiting for results", "impatience, effort without reward"],
    ["dedication, craft, attention to detail", "perfectionism, routine"],
    ["independence, well-earned luxury", "financial dependence"],
    ["wealth, family, legacy", "losses, inheritance disputes"],
    ["study, practical ambition, money news", "lack of focus, laziness"],
    ["consistency, routine, responsibility", "stagnation, boredom"],
    ["practicality, nurturing, abundance", "neglect, work-home imbalance"],
    ["wealth, success, security", "materialism, stubbornness"],
  ],
};

const IDS_RANGO = ["as", "dos", "tres", "cuatro", "cinco", "seis", "siete", "ocho", "nueve", "diez", "sota", "caballo", "reina", "rey"];

function construirMenores() {
  const lista = [];
  for (const [palo, datos] of Object.entries(PALOS)) {
    RANGOS.forEach((rango, i) => {
      const [cd, ci] = CLAVES_MENORES[palo][i];
      const nombre = `${rango.nombre} of ${datos.nombre}`;
      lista.push({
        id: `${IDS_RANGO[i]}-de-${palo}`,
        nombre, palo, rango: rango.r, glifo: datos.glifo, astro: datos.elemento,
        claves: cd.split(", "), invertidas: ci.split(", "),
        derecho: `The ${nombre} belongs to the realm of ${datos.ambito}. It represents ${rango.sentido}. Its keywords: ${cd}.`,
        invertido: `Reversed, the card points to ${rango.inv} in matters of ${datos.corto}. Its keywords: ${ci}.`,
        amor: palo === "copas" ? `Very important in matters of the heart: ${cd}.` : `In love, applied to the relationship: ${cd}.`,
        trabajo: palo === "oros" || palo === "bastos" ? `Very relevant at work: ${cd}.` : `At work: ${cd}.`,
        consejo: `The key right now: ${cd.split(", ")[0]}.`,
        sino: rango.r === 5 || (palo === "espadas" && [3, 8, 9, 10].includes(rango.r)) ? "no" : ([4, 7, 12].includes(rango.r) ? "quizás" : "sí"),
      });
    });
  }
  return lista;
}

const ARCANOS_MENORES = construirMenores();
const MAZO = [...ARCANOS_MAYORES.map(c => ({ ...c, mayor: true })), ...ARCANOS_MENORES.map(c => ({ ...c, mayor: false }))];
const cartaPorId = id => MAZO.find(c => c.id === id);

const NUMERALES = ["0", "I", "II", "III", "IV", "V", "VI", "VII", "VIII", "IX", "X", "XI", "XII", "XIII", "XIV", "XV", "XVI", "XVII", "XVIII", "XIX", "XX", "XXI"];
